

SELECT DATE , TOTAL_BOOKING
FROM GOLD_AGG_DAILY_BOOKING
ORDER BY DATE ;


SELECT HOTEL_CITY , TOTAL_REVENUE 
FROM GOLD_AGG_HOTEL_CITY_SALES 
WHERE TOTAL_REVENUE IS NOT NULL
ORDER BY TOTAL_REVENUE DESC 
LIMIT 5;


--Bar Chart - Bookings by Type
SELECT room_type, COUNT(*) AS total_bookings
FROM GOLD_BOOKING_CLEAN
GROUP BY room_type
ORDER BY total_bookings DESC;